#!/usr/bin/env node
// Generates js/firebase-config.js AND js/supabase-config.js from environment
// variables. Runs automatically on Netlify as the build command (see
// netlify.toml), using whatever you've set under Site settings ->
// Environment variables. Both output files are gitignored — your real keys
// never touch git.
//
// Locally, you can either:
//   1. Create a .env file in the project root (see .env.example) and run
//      `node scripts/generate-config.js`, or
//   2. Skip this entirely and copy js/firebase-config.example.js and
//      js/supabase-config.example.js to their non-.example names, filling
//      in values by hand.

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const ENV_FILE = path.join(ROOT, ".env");

// Minimal .env loader — no dependency needed for something this small.
// Real environment variables (e.g. the ones Netlify injects) always take
// priority over a local .env file.
function loadDotEnv() {
  if (!fs.existsSync(ENV_FILE)) return;
  const lines = fs.readFileSync(ENV_FILE, "utf8").split("\n");
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    value = value.replace(/^["']|["']$/g, "");
    if (!(key in process.env)) process.env[key] = value;
  }
}

loadDotEnv();

function requireVars(keys) {
  const missing = keys.filter((k) => !process.env[k]);
  if (missing.length) {
    console.error("\nMissing required environment variables:\n  " + missing.join("\n  "));
    console.error(
      "\nSet these in Netlify under Site settings -> Environment variables, " +
      "or in a local .env file (see .env.example).\n"
    );
    process.exit(1);
  }
}

/* ---- Firebase: Firestore (real-time sync) + Anonymous Auth ---- */
requireVars([
  "FIREBASE_API_KEY",
  "FIREBASE_AUTH_DOMAIN",
  "FIREBASE_PROJECT_ID",
  "FIREBASE_STORAGE_BUCKET",
  "FIREBASE_MESSAGING_SENDER_ID",
  "FIREBASE_APP_ID"
]);

const firebaseOut = path.join(ROOT, "js", "firebase-config.js");
fs.writeFileSync(firebaseOut, `// AUTO-GENERATED by scripts/generate-config.js — do not edit by hand and
// do not commit this file (it's gitignored). Change the environment
// variables instead and re-run the build.

export const firebaseConfig = {
  apiKey: "${process.env.FIREBASE_API_KEY}",
  authDomain: "${process.env.FIREBASE_AUTH_DOMAIN}",
  projectId: "${process.env.FIREBASE_PROJECT_ID}",
  storageBucket: "${process.env.FIREBASE_STORAGE_BUCKET}",
  messagingSenderId: "${process.env.FIREBASE_MESSAGING_SENDER_ID}",
  appId: "${process.env.FIREBASE_APP_ID}"
};
`);
console.log("Wrote js/firebase-config.js from environment variables.");

/* ---- Supabase: Storage (files & images) ---- */
requireVars(["SUPABASE_URL", "SUPABASE_ANON_KEY"]);

const supabaseOut = path.join(ROOT, "js", "supabase-config.js");
fs.writeFileSync(supabaseOut, `// AUTO-GENERATED by scripts/generate-config.js — do not edit by hand and
// do not commit this file (it's gitignored). Change the environment
// variables instead and re-run the build.

export const supabaseConfig = {
  url: "${process.env.SUPABASE_URL}",
  anonKey: "${process.env.SUPABASE_ANON_KEY}"
};
`);
console.log("Wrote js/supabase-config.js from environment variables.");
